track:
  name: "FSG"
  start:
    x: 0.0
    y: 0.0
    heading: 0.0
  cones:
    blue:    # Right boundary
      - [3.0, -1.5]
      - [8.0, -1.5]
      - [13.0, -1.5]
      - [18.0, -1.5]
      - [23.0, -2.0]
      - [28.0, -3.0]
      - [32.0, -5.0]
      - [35.0, -8.0]
      - [36.0, -12.0]
      - [35.0, -16.0]
      - [32.0, -19.0]
      - [28.0, -21.0]
      - [23.0, -22.0]
      - [18.0, -22.0]
      - [13.0, -21.0]
      - [8.0, -19.0]
      - [4.0, -16.0]
      - [2.0, -12.0]
      - [2.0, -8.0]
      - [4.0, -5.0]
      - [0.0, -3.0]
    yellow:  # Left boundary
      - [3.0, 1.5]
      - [8.0, 1.5]
      - [13.0, 1.5]
      - [18.0, 1.5]
      - [23.0, 1.0]
      - [28.0, 0.0]
      - [32.0, -2.0]
      - [35.0, -5.0]
      - [36.0, -9.0]
      - [35.0, -13.0]
      - [32.0, -16.0]
      - [28.0, -18.0]
      - [23.0, -19.0]
      - [18.0, -19.0]
      - [13.0, -18.0]
      - [8.0, -16.0]
      - [4.0, -13.0]
      - [2.0, -9.0]
      - [2.0, -5.0]
      - [4.0, -2.0]
      - [0.0, 0.0]
    orange:  # Start/finish
      - [0.0, -1.5]
      - [0.0, 1.5]
    orange_big:
      - [-1.0, -2.5]
      - [-1.0, 2.5]
